### ISSUE TITLE
Как добавлять каналы?

### ISSUE THREAD

**Issue by STARTSPr0** [andreyru02/telegram-grabber#4]
Как добавить каналы? Все сделал по инструкции, все робит, но не пойму что совать боту. Название каналов писал, ссылку на канал вставлять, он все равно не видит посты, хотя в бд все заносит. Покажи на примере

**Comment by andreyru02** [comment]
> Как добавить каналы? Все сделал по инструкции, все робит, но не пойму что совать боту. Название каналов писал, ссылку на канал вставлять, он все равно не видит посты, хотя в бд все заносит. Покажи на примере

Привет. Как я понял, ты БД заполнил донорами, модером и основным каналом.
И у тебя проблема в том, что когда в доноре создается новый пост тебе в канал модера он не приходит?
Первое, что сразу приходит в голову это нужно быть подписанным на канал донора.

**Comment by STARTSPr0** [comment]
Я подписан само собой. Просто покажи пример на одном канале, вдруг что-то не так делаю. К примеру возьмем канал МДК (там просто часто что-то выходит) https://t.me/mudak  . Я добавил в бота ссылку mukdak. Правильно или нет?

**Comment by andreyru02** [comment]
> Я подписан само собой. Просто покажи пример на одном канале, вдруг что-то не так делаю. К примеру возьмем канал МДК (там просто часто что-то выходит) https://t.me/mudak . Я добавил в бота ссылку mukdak. Правильно или нет? Может ид канала нужно пихать?

Ну да, все правильно. Если ссылка на канал https://t.me/python_skills , то нужно писать python_skills.
Я даже не могу понять, в чем может быть проблема.. Попробуй сделать себя админом в канале модера..

**Comment by STARTSPr0** [comment]
Я создатель в канале модера, админ права само собой имеются, но в логе пишет что нет прав на отправку 

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pyrogram/dispatcher.py", line 219, in handler_worker
    await self.loop.run_in_executor(
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "./bot_grabber.py", line 35, in get_post
    message.forward(bd.get_moder())
  File "/usr/local/lib/python3.8/dist-packages/pyrogram/sync.py", line 50, in async_to_sync_wrap
    return asyncio.run_coroutine_threadsafe(coroutine, loop).result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.8/dist-packages/pyrogram/types/messages_and_media/message.py", line 2815, in forward
    return await self._client.forward_messages(
  File "/usr/local/lib/python3.8/dist-packages/pyrogram/methods/messages/forward_messages.py", line 78, in forward_messages
    r = await self.send(
  File "/usr/local/lib/python3.8/dist-packages/pyrogram/methods/advanced/send.py", line 77, in send
    r = await self.session.send(
  File "/usr/local/lib/python3.8/dist-packages/pyrogram/session/session.py", line 425, in send
    return await self._send(data, timeout=timeout)
  File "/usr/local/lib/python3.8/dist-packages/pyrogram/session/session.py", line 395, in _send
    RPCError.raise_it(result, type(data))
  File "/usr/local/lib/python3.8/dist-packages/pyrogram/errors/rpc_error.py", line 78, in raise_it
    raise getattr(
pyrogram.errors.exceptions.forbidden_403.ChatWriteForbidden: [403 CHAT_WRITE_FORBIDDEN]: You don't have rights to send messages in this chat (caused by "messages.ForwardMessages")

**Comment by andreyru02** [comment]
Попробуй отработать по созданию бота и добавить его в админы. 
https://docs.pyrogram.org/start/auth
Этот момент я видимо упустил при написании инструкции.
У меня есть бот, я его создавал еще когда только начинал этим всем заниматься и он в работе. Имеет доступ к сообщениями и через него можно публиковать посты в канал.
Но я не помню, как он вообще функционирует, ведь при запуске pyrogram я нигде не указываю токен от этого бота..

**Comment by STARTSPr0** [comment]
Добавил бота в канал модера и в главный канал, все права выдал, ошибка точно такая же

**Comment by andreyru02** [comment]
> Добавил бота в канал модера и в главный канал, все права выдал, ошибка точно такая же

Попробуй тогда зайти в бота Controller Bot -> /start -> /addchannel и добавить туда модера и свой канал.

**Comment by STARTSPr0** [comment]
Он тогда не может перехватить управление 

Cause exception while getting updates.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/aiogram/dispatcher/dispatcher.py", line 383, in start_polling
    updates = await self.bot.get_updates(
  File "/usr/local/lib/python3.8/dist-packages/aiogram/bot/bot.py", line 97, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
  File "/usr/local/lib/python3.8/dist-packages/aiogram/bot/base.py", line 208, in request
    return await api.make_request(self.session, self.server, self.__token, method, data, files,
  File "/usr/local/lib/python3.8/dist-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
  File "/usr/local/lib/python3.8/dist-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/usr/local/lib/python3.8/dist-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.CantGetUpdates: Can't use getupdates method while webhook is active; use deletewebhook to delete the webhook first

**Comment by andreyru02** [comment]
Что то странно все и не понятно. Я точно не припоминаю таких проблем у себя.
Нагуглил, что можно попробовать сделать revoke в botfather 'revoke current token'.

**Comment by STARTSPr0** [comment]
Да, после смены токена Controller Bot больше не имеет власти, контроль вернулся, но ошибка с нехваткой прав так и осталась

**Comment by andreyru02** [comment]
Я вечером попробую на новых акк запуститься, если такие же ошибки будут, попробую разобраться.

**Comment by STARTSPr0** [comment]
Благодарю

**Comment by STARTSPr0** [comment]
Кажется добился чтобы все заработало. как всегда виноват юзер, а не автор. 
Канал модера был приватным, сделал публичным, заново добавил в бота канал и заработало, благодарю за помощь

**Comment by STARTSPr0** [comment]
Но появилась другая проблема :D 
При отправке номера поста чтобы он запостил в основной такая ошибка

forward() got an unexpected keyword argument 'as_copy'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pyrogram/dispatcher.py", line 219, in handler_worker
    await self.loop.run_in_executor(
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "../python_bot/bot_grabber.py", line 47, in send_post
    send.forward(bd.get_channel(), as_copy=True)
  File "/usr/local/lib/python3.8/dist-packages/pyrogram/sync.py", line 38, in async_to_sync_wrap
    coroutine = function(*args, **kwargs)
TypeError: forward() got an unexpected keyword argument 'as_copy'

**Comment by andreyru02** [comment]
> Кажется добился чтобы все заработало. как всегда виноват юзер, а не автор.
> Канал модера был приватным, сделал публичным, заново добавил в бота канал и заработало, благодарю за помощь

Как я сам то не догадался спросить у тебя.)



> При отправке номера поста чтобы он запостил в основной такая ошибка


> TypeError: forward() got an unexpected keyword argument 'as_copy'

А версия pyrogram какая стоит? Нужна Pyrogram==1.0.7

**Comment by STARTSPr0** [comment]
1.2.9  стоит. Там апи поменялось что ли?

**Comment by andreyru02** [comment]
> 1.2.9 стоит. Там апи поменялось что ли?

Вроде as_copy в методе forward теперь нету.

**Comment by STARTSPr0** [comment]
да, после удаления заработало, благодарю
